<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\StoredProcedure>
 */
class StoredProcedureFactory extends Factory
{ 
    public function definition()
    {return [
        'docno' => rand(1111,9999),
        'Ncode' => '0'.rand(600000000,69999999),
        'fname' => $this->faker->firstName,
        'lname' => $this->faker->lastName,
        'FatherName' => $this->faker->firstName,
        'passno' => '0'.rand(600000000,69999999),
        'birthdate' => $this->faker->date(),
        'birthplace' => $this->faker->city,
        'sex' => $this->faker->randomElement([1,2]),
        'marital' => $this->faker->randomElement([1,2,3,4,5]), 
        'religion' => $this->faker->randomElement([1,2,3,4]), 
        'job' => $this->faker->word(),
        'organization' => $this->faker->randomElement([1,2]),
        'tel' => '056324'.rand(00000,99999),
        'mob' => '0915'.rand(0000000,9999999), 
        'address' => $this->faker->address(), 
        'mname' => $this->faker->firstName(), 
        'mtel' => '0915'.rand(0000000,9999999), 
        'maddress' => $this->faker->address(), 
        'hisno' => $this->faker->numberBetween(000000,999999),
        'pdate' => $this->faker->date,
        'ptime' => $this->faker->time(),
        'ward' => $this->faker->randomElement([1,2,3,4]),
        'bed' => $this->faker->randomElement([1,2]), 
        'doctor' => $this->faker->randomElement([1,2]),
        'admission' => $this->faker->randomElement([1,2,3,4]), 
        'police' => $this->faker->randomElement(['کلانتری شعبه 25' , 'کلانتری شعبه 69']),
        'intype' => $this->faker->randomElement([1,2,3,4,5,6,7,8]),
        'inno' => rand(111111,999999),
        'tdate' => $this->faker->date(), 
        'ttime' => $this->faker->time(), 
        'ttype' => rand(1,1000), 
        'tdesc' => rand(1,1000),
        'tadesc' => rand(1,1000),
        'isconsultation' => $this->faker->randomElement(['بله' , 'خیر']),
        'tadvice' => rand(1,10),
        'tstay' => $this->faker->numberBetween(0, 10),
        'tndate' => $this->faker->date(), 
        'isdead' => 0, 
        'fdate' => null,
        'ftime' => null,
        'fdesc' => rand(1,1000), 
        'hospitaltest' => rand(1,1000), 
        'firstrecognition' => rand(1,1000), 
        'duringrecognition' => rand(1,1000), 
        'lastrecognition' => rand(1,1000), 
        'externalcause' => rand(1,1000), 
        'surgery' => rand(1,1000), 
        'surgreycode' => rand(1,1000), 
        'surgreydate' => $this->faker->date(),
        'emrcode' => rand(11111,99999), 
    ];
        // return [
        //     'docno' => $this->faker->numberBetween(1, 100),
        //     'Ncode' => $this->faker->numberBetween(1, 100),
        //     'fname' => $this->faker->firstName,
        //     'lname' => $this->faker->lastName,
        //     'FatherName' => $this->faker->lastName, 
        //     'passno' => $this->faker->numberBetween(1, 100), 
        //     'birthdate' => $this->faker->dateTimeBetween('-60 years', '-18 years'), 
        //     'birthplace' => $this->faker->city, 
        //     'sex' => $this->faker->randomElement(['مرد', 'زن']),
        //     'marital' => $this->faker->randomElement(['مجرد', 'متاهل']),
        //     'religion' => $this->faker->randomElement(['مسلمان', 'مسیحی']),
        //     'job' => $this->faker->word(), 
        //     'organization' => $this->faker->word(), 
        //     'tel' => $this->faker->phoneNumber, 
        //     'mob' => $this->faker->phoneNumber, 
        //     'address' => $this->faker->address, 
        //     'mname' => $this->faker->firstName,
        //     'mtel' => $this->faker->phoneNumber,  
        //     'maddress' => $this->faker->city, 
        //     'hisno' => $this->faker->unique()->numberBetween(1, 100000000000000),
        //     'pdate' => $this->faker->dateTimeBetween('-60 years', '-18 years'), 
        //     'ptime' => $this->faker->time(),
        //     'ward' => $this->faker->word(),
        //     'bed' => $this->faker->word(),
        //     'doctor' => $this->faker->name,
        //     'admission' => $this->faker->word(),
        //     'police' => $this->faker->word(),
        //     'intype' => $this->faker->word(),
        //     'inno' => $this->faker->numberBetween(1, 100),
        //     'tdate' => $this->faker->dateTimeBetween('-60 years', '-18 years'),
        //     'ttime' => $this->faker->time(),
        //     'ttype' => $this->faker->word(),
        //     'tdesc' => $this->faker->word(),
        //     'tadesc' => $this->faker->word(),
        //     'isconsultation' => $this->faker->word(),
        //     'tadvice' => $this->faker->word(),
        //     'tstay' => $this->faker->word(),
        //     'tndate' => $this->faker->dateTimeBetween('-60 years', '-18 years'),
        //     'isdead' => $this->faker->word(),
        //     'fdate' => $this->faker->dateTimeBetween('-60 years', '-18 years'),
        //     'ftime' => $this->faker->time(),
        //     'fdesc' => $this->faker->word(),
        //     'hospitaltest' => $this->faker->word(),
        //     'firstrecognition' => $this->faker->word(),
        //     'duringrecognition' => $this->faker->word(),
        //     'lastrecognition' => $this->faker->word(),
        //     'externalcause' => $this->faker->word(),
        //     'surgery' => $this->faker->word(),
        //     'surgreycode' => $this->faker->word(),
        //     'surgreydate' => $this->faker->dateTimeBetween('-60 years', '-18 years'),
        //     'emrcode' => $this->faker->numberBetween(1, 100),
        // ];
    }
}
